spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # (create, create-drop, update, validate 등으로 설정 가능)
    show-sql: true  # SQL 쿼리 로깅
    properties:
      hibernate:
        format_sql: true # SQL 쿼리 포맷팅
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json
